name: lexa
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.0.221=h6bb024c_0
  - python=3.6.12=hcff3b4d_2
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py36h5fab9bb_1
  - ffmpeg=4.3.1=hca11adc_2
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - lame=3.100=h7f98852_1001
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgomp=9.3.0=h2828fa1_19
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=h6de172a_19
  - nettle=3.6=he412f7d_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1k=h7f98852_0
  - python_abi=3.6=1_cp36m
  - x264=1!161.3030=h7f98852_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - ncurses=6.2=he6710b0_1
  - pip=21.0.1=py36h06a4308_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py36h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.12.0
    - astunparse==1.6.3
    - atari-py==0.2.6
    - backcall==0.2.0
    - cachetools==4.2.2
    - cffi==1.14.5
    - chardet==4.0.0
    - click==8.0.0
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - cython==0.29.23
    - decorator==5.0.7
    - dm-control==0.0.364896371
    - dm-env==1.4
    - dm-tree==0.1.6
    - fasteners==0.16
    - flatbuffers==1.12
    - future==0.18.2
    - gast==0.3.3
    - glfw==2.1.0
    - google-auth==1.30.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - gym==0.18.0
    - h5py==2.10.0
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==4.0.1
    - ipdb==0.13.7
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - labmaze==1.0.4
    - llvmlite==0.36.0
    - lxml==4.6.3
    - markdown==3.3.4
    - matplotlib==3.3.4
    - mujoco-py==2.0.2.13
    - numba==0.53.1
    - numpy==1.19.5
    - numpy-quaternion==2021.4.5.14.42.35
    - oauthlib==3.1.0
    - opencv-python==4.5.2.52
    - opt-einsum==3.3.0
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - prompt-toolkit==3.0.18
    - protobuf==3.16.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyglet==1.5.0
    - pygments==2.9.0
    - pyopengl==3.1.5
    - pyparsing==2.4.7
    - pyquaternion==0.9.9
    - python-dateutil==2.8.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - ruamel.yaml==0.17.4
    - ruamel.yaml.clib==0.2.2
    - scipy==1.5.4
    - six==1.15.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.0
    - tensorflow-estimator==2.4.0
    - tensorflow-probability==0.11.1
    - termcolor==1.1.0
    - toml==0.10.2
    - tqdm==4.60.0
    - traitlets==4.3.3
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - wcwidth==0.2.5
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.4.1
